version: "3.9"

services:
  db:
    container_name: artisan-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: artisan
      MYSQL_USER: artisan
      MYSQL_PASSWORD: artisan
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  app:
    container_name: artisan-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8091
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/artisan?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: artisan
      SPRING_DATASOURCE_PASSWORD: artisan
      APP_JWT_SECRET: changeme-dev-secret
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8091:8091"
    restart: unless-stopped

volumes:
  db_data: